### PR TITLE
Add a test for the /users table

### PR DESCRIPTION
**Pull request by shadow7**
[770f4bc] the test passes
[e4c8aa8] auth ref missing
[4ff176a] update user routes with firebase store injection
[9389cca] correct references
[d8b9093] call npm test to start all testing resources
[7a9c129] abstract firebase store and inject it in to requiring modules through their constructors
[b447593] clean up authentication file
[c5fe448] create authentication singleton that takes in a firebase store
[46218c6] call npm update
add mocha for testing framework
add assert for assertions
add simon for method stubs
add nock for mock requests
add istanbul for test coverage

### CODE REVIEW

**Comment by shadow7** [comment]
@ChrisCoffey module exports make sense but I'm definitely far from mastering concise syntax in js. This commit abstracts the firebase object so that it is an input dependency for all middleware functions. I did this so that we can switch the firebase store endpoint depending on if we are in test, development, or production. You should also be able to run the single test i've created with "npm test". Let me know what you think

**Comment by bucchino** [comment]
Neat.

**Comment by ChrisCoffey** [comment]
One thing I'd prefer is actually less squashing, or if you are squashing please change the commit message to not list all of the individual commits. Commit messages really should describe the commit, and if a bunch of commits are squashed then it doesn't really matter that they existed.

**Comment by shadow7** [comment]
sure, ill fix that going forward

**Comment by shadow7** [comment]
sure, I'll change that going forward

**Comment by ChrisCoffey** [comment]
I'd like to merge this before it gets too big. Please don't make unrelated commits in this branch, fork off and make any separate refactorings

**Pull request merged**
