### PR TITLE
Add Mongo DB client library

### PR DESCRIPTION
**Pull request by ChrisCoffey**
This uses Mongoose, a solid mongo client library.

### CODE REVIEW

**Comment by shadow7** [comment]
Looks good to me, can you squash these?

**Comment by shadow7** [comment]
@ChrisCoffey Do you want to join the slack group again for messaging? Or do you just want to stick to github and email.

**Comment by ChrisCoffey** [comment]
Slack's fine for anything not related to a pull, but for thing specific to
a pull request I want to keep that on GH. I'll hop back on slack later
today.

**Comment by shadow7** [comment]
updated to #15

**Pull request closed without merging**
